use_frameworks!

target 'Redux-ReactiveSwift_Example' do
  pod 'Redux-ReactiveSwift', :path => '../'

  target 'Redux-ReactiveSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
