platform :ios do
  lane :cocoapods_test do
    cocoapods(repo_update: true, verbose: true)
    scan(
		workspace: 'Redux-ReactiveSwift.xcworkspace',
		scheme: 'CocoaPods-Redux-ReactiveSwift-iOS',
		code_coverage: true,
		clean: true,
		output_types: "html",
		devices: ["iPhone 8"]	
    )
    xcov(
		workspace: 'Redux-ReactiveSwift.xcworkspace',		
		scheme: 'CocoaPods-Redux-ReactiveSwift-iOS',
		output_directory: '.xcov',
		derived_data_path: lane_context[SharedValues::SCAN_DERIVED_DATA_PATH],
		skip_slack: true
    )
  end
  lane :carthage_test do
    carthage
    scan(
		project: 'Redux-ReactiveSwift.xcodeproj',
		scheme: 'Carthage-Redux-ReactiveSwift-iOS',
		code_coverage: true,
		clean: true,
		output_types: "html",
		devices: ["iPhone 8"]	
    )
    xcov(
		project: 'Redux-ReactiveSwift.xcodeproj',		
		scheme: 'Carthage-Redux-ReactiveSwift-iOS',
		output_directory: '.xcov',
		derived_data_path: lane_context[SharedValues::SCAN_DERIVED_DATA_PATH],
		skip_slack: true
    )  
  end
end
