source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
    
def common_pods
	pod 'ReactiveSwift', '~> 4.0'
end

def test_pods
    pod 'Quick', '1.2.0'
    pod 'Nimble', '7.0.3'
    pod 'ReactiveCocoa', '~> 8.0'
end

def app_pods
end

test_targets = ['CocoaPods-Redux-ReactiveSwift-iOSTests']
app_targets = ['CocoaPods-Redux-ReactiveSwift-watchOS', 'CocoaPods-Redux-ReactiveSwift-tvOS', 'CocoaPods-Redux-ReactiveSwift-iOS', 'CocoaPods-Redux-ReactiveSwift-macOS']

test_targets.each { |targetName|
    target targetName do
        common_pods
        test_pods
    end
}

app_targets.each { |targetName|
    target targetName do
        common_pods
        app_pods
    end
}
